accounts:
  - name: validator1
    coins: ["10000000ssvt"]
  - name: jacob
    coins: ["10000000ssvt"]
validator:
  name: validator1
  staked: "1000000ssvt"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
init:
  client:
    keyring-backend: "test"
genesis:
  chain_id: "cosmos:smpl-secrets-vault"
  app_state:
    staking:
      params:
        bond_denom: "ssvt"
    crisis:
      constant_fee:
        denom: ssvt
    mint:
      params:
        mint_denom: ssvt