// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: smplsecretsvaultchain/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dc0433211492f76, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dc0433211492f76, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetPassportRequest struct {
}

func (m *QueryGetPassportRequest) Reset()         { *m = QueryGetPassportRequest{} }
func (m *QueryGetPassportRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetPassportRequest) ProtoMessage()    {}
func (*QueryGetPassportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dc0433211492f76, []int{2}
}
func (m *QueryGetPassportRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPassportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPassportRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPassportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPassportRequest.Merge(m, src)
}
func (m *QueryGetPassportRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPassportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPassportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPassportRequest proto.InternalMessageInfo

type QueryGetPassportResponse struct {
	Passport Passport `protobuf:"bytes,1,opt,name=Passport,proto3" json:"Passport"`
}

func (m *QueryGetPassportResponse) Reset()         { *m = QueryGetPassportResponse{} }
func (m *QueryGetPassportResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetPassportResponse) ProtoMessage()    {}
func (*QueryGetPassportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dc0433211492f76, []int{3}
}
func (m *QueryGetPassportResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPassportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPassportResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPassportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPassportResponse.Merge(m, src)
}
func (m *QueryGetPassportResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPassportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPassportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPassportResponse proto.InternalMessageInfo

func (m *QueryGetPassportResponse) GetPassport() Passport {
	if m != nil {
		return m.Passport
	}
	return Passport{}
}

type QueryGetPassportStorageRequest struct {
}

func (m *QueryGetPassportStorageRequest) Reset()         { *m = QueryGetPassportStorageRequest{} }
func (m *QueryGetPassportStorageRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetPassportStorageRequest) ProtoMessage()    {}
func (*QueryGetPassportStorageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dc0433211492f76, []int{4}
}
func (m *QueryGetPassportStorageRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPassportStorageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPassportStorageRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPassportStorageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPassportStorageRequest.Merge(m, src)
}
func (m *QueryGetPassportStorageRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPassportStorageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPassportStorageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPassportStorageRequest proto.InternalMessageInfo

type QueryGetPassportStorageResponse struct {
	PassportStorage PassportStorage `protobuf:"bytes,1,opt,name=PassportStorage,proto3" json:"PassportStorage"`
}

func (m *QueryGetPassportStorageResponse) Reset()         { *m = QueryGetPassportStorageResponse{} }
func (m *QueryGetPassportStorageResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetPassportStorageResponse) ProtoMessage()    {}
func (*QueryGetPassportStorageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dc0433211492f76, []int{5}
}
func (m *QueryGetPassportStorageResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPassportStorageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPassportStorageResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPassportStorageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPassportStorageResponse.Merge(m, src)
}
func (m *QueryGetPassportStorageResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPassportStorageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPassportStorageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPassportStorageResponse proto.InternalMessageInfo

func (m *QueryGetPassportStorageResponse) GetPassportStorage() PassportStorage {
	if m != nil {
		return m.PassportStorage
	}
	return PassportStorage{}
}

type QueryGetPassportsRequest struct {
}

func (m *QueryGetPassportsRequest) Reset()         { *m = QueryGetPassportsRequest{} }
func (m *QueryGetPassportsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetPassportsRequest) ProtoMessage()    {}
func (*QueryGetPassportsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dc0433211492f76, []int{6}
}
func (m *QueryGetPassportsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPassportsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPassportsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPassportsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPassportsRequest.Merge(m, src)
}
func (m *QueryGetPassportsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPassportsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPassportsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPassportsRequest proto.InternalMessageInfo

type QueryGetPassportsResponse struct {
	Passports Passports `protobuf:"bytes,1,opt,name=Passports,proto3" json:"Passports"`
}

func (m *QueryGetPassportsResponse) Reset()         { *m = QueryGetPassportsResponse{} }
func (m *QueryGetPassportsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetPassportsResponse) ProtoMessage()    {}
func (*QueryGetPassportsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dc0433211492f76, []int{7}
}
func (m *QueryGetPassportsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPassportsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPassportsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPassportsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPassportsResponse.Merge(m, src)
}
func (m *QueryGetPassportsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPassportsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPassportsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPassportsResponse proto.InternalMessageInfo

func (m *QueryGetPassportsResponse) GetPassports() Passports {
	if m != nil {
		return m.Passports
	}
	return Passports{}
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "SmplFinance.smplsecretsvaultchain.smplsecretsvaultchain.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "SmplFinance.smplsecretsvaultchain.smplsecretsvaultchain.QueryParamsResponse")
	proto.RegisterType((*QueryGetPassportRequest)(nil), "SmplFinance.smplsecretsvaultchain.smplsecretsvaultchain.QueryGetPassportRequest")
	proto.RegisterType((*QueryGetPassportResponse)(nil), "SmplFinance.smplsecretsvaultchain.smplsecretsvaultchain.QueryGetPassportResponse")
	proto.RegisterType((*QueryGetPassportStorageRequest)(nil), "SmplFinance.smplsecretsvaultchain.smplsecretsvaultchain.QueryGetPassportStorageRequest")
	proto.RegisterType((*QueryGetPassportStorageResponse)(nil), "SmplFinance.smplsecretsvaultchain.smplsecretsvaultchain.QueryGetPassportStorageResponse")
	proto.RegisterType((*QueryGetPassportsRequest)(nil), "SmplFinance.smplsecretsvaultchain.smplsecretsvaultchain.QueryGetPassportsRequest")
	proto.RegisterType((*QueryGetPassportsResponse)(nil), "SmplFinance.smplsecretsvaultchain.smplsecretsvaultchain.QueryGetPassportsResponse")
}

func init() { proto.RegisterFile("smplsecretsvaultchain/query.proto", fileDescriptor_5dc0433211492f76) }

var fileDescriptor_5dc0433211492f76 = []byte{
	// 550 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0x4f, 0x6b, 0x13, 0x41,
	0x18, 0xc6, 0x33, 0x45, 0x43, 0x1d, 0x0f, 0xc2, 0x58, 0xb0, 0x5d, 0x64, 0x5b, 0x17, 0x05, 0x11,
	0xc9, 0xd0, 0x7a, 0xf0, 0x58, 0x92, 0x8a, 0xb5, 0xad, 0x87, 0xfc, 0x01, 0x15, 0x41, 0x64, 0xb2,
	0x8e, 0xdb, 0x85, 0xec, 0xce, 0x74, 0x67, 0x52, 0xda, 0x93, 0xa0, 0x77, 0x11, 0x3c, 0x78, 0xf0,
	0x0b, 0xf5, 0x58, 0xf0, 0xe2, 0x49, 0x24, 0xf1, 0xe8, 0x27, 0xf0, 0x20, 0x25, 0x33, 0xef, 0xa6,
	0x4d, 0x76, 0x93, 0x43, 0x77, 0x6f, 0xcb, 0xcc, 0xc3, 0xf3, 0xfe, 0xde, 0x67, 0xe6, 0x9d, 0xc5,
	0x77, 0x54, 0x24, 0x7b, 0x8a, 0xfb, 0x09, 0xd7, 0xea, 0x90, 0xf5, 0x7b, 0xda, 0xdf, 0x67, 0x61,
	0x4c, 0x0f, 0xfa, 0x3c, 0x39, 0xae, 0xc9, 0x44, 0x68, 0x41, 0x1e, 0x77, 0x22, 0xd9, 0x7b, 0x1a,
	0xc6, 0x2c, 0xf6, 0x79, 0x2d, 0x57, 0x9e, 0xbf, 0xea, 0x2c, 0x05, 0x22, 0x10, 0xc6, 0x83, 0x8e,
	0xbe, 0xac, 0x9d, 0x73, 0x3b, 0x10, 0x22, 0xe8, 0x71, 0xca, 0x64, 0x48, 0x59, 0x1c, 0x0b, 0xcd,
	0x74, 0x28, 0x62, 0x05, 0xbb, 0x0f, 0x7c, 0xa1, 0x22, 0xa1, 0x68, 0x97, 0x29, 0x6e, 0x29, 0xe8,
	0xe1, 0x7a, 0x97, 0x6b, 0xb6, 0x4e, 0x25, 0x0b, 0xc2, 0xd8, 0x88, 0x41, 0xeb, 0xe5, 0xb3, 0x4b,
	0x96, 0xb0, 0x28, 0xf5, 0xbb, 0x3b, 0x4b, 0xa3, 0x94, 0x14, 0x89, 0x06, 0xd5, 0xc3, 0xf9, 0xaa,
	0xb7, 0x4a, 0x8b, 0x84, 0x05, 0x1c, 0xd4, 0xf7, 0xe6, 0xab, 0xa1, 0xb4, 0xb7, 0x84, 0x49, 0x6b,
	0xd4, 0x40, 0xd3, 0xf0, 0xb4, 0xf9, 0x41, 0x9f, 0x2b, 0xed, 0x69, 0x7c, 0x73, 0x62, 0x55, 0x49,
	0x11, 0x2b, 0x4e, 0xde, 0xe0, 0xaa, 0xe5, 0x5e, 0x46, 0x6b, 0xe8, 0xfe, 0xf5, 0x8d, 0xcd, 0xda,
	0x25, 0x53, 0xaf, 0x59, 0xe3, 0xc6, 0x95, 0x93, 0x5f, 0xab, 0x95, 0x36, 0x98, 0x7a, 0x2b, 0xf8,
	0x96, 0xa9, 0xba, 0xcd, 0x75, 0x13, 0x30, 0x53, 0xa0, 0x0f, 0x78, 0x39, 0xbb, 0x05, 0x54, 0x3e,
	0x5e, 0x4c, 0xd7, 0x80, 0xab, 0x5e, 0x80, 0xcb, 0x1a, 0x01, 0xd9, 0xd8, 0xd8, 0x5b, 0xc3, 0xee,
	0x34, 0x40, 0xc7, 0xe6, 0x9d, 0x22, 0x7e, 0x47, 0x78, 0x75, 0xa6, 0x04, 0x50, 0x8f, 0xf0, 0x8d,
	0xa9, 0x2d, 0x20, 0x7e, 0x56, 0x98, 0x18, 0xfc, 0x00, 0x7c, 0xba, 0x8c, 0xe7, 0x64, 0x03, 0x1c,
	0x9f, 0xf6, 0x27, 0x84, 0x57, 0x72, 0x36, 0x81, 0xf9, 0x3d, 0xbe, 0x36, 0x5e, 0x04, 0xda, 0x46,
	0x61, 0xda, 0xf4, 0xe8, 0xcf, 0xad, 0x37, 0x3e, 0x2f, 0xe2, 0xab, 0x86, 0x82, 0xfc, 0x45, 0xb8,
	0x6a, 0x2f, 0x08, 0xd9, 0xbb, 0x74, 0xa5, 0xec, 0xad, 0x76, 0x9e, 0x97, 0x63, 0x66, 0x73, 0xf1,
	0xb6, 0x3f, 0xfe, 0xf8, 0xf3, 0x75, 0xa1, 0x4e, 0x36, 0xe9, 0x05, 0x57, 0x9a, 0x3f, 0x75, 0xf3,
	0xde, 0x00, 0xf2, 0x0f, 0x9d, 0x5f, 0x60, 0xd2, 0x2c, 0xc6, 0x98, 0x1d, 0x1d, 0xa7, 0x55, 0xa2,
	0x23, 0xb4, 0xbe, 0x63, 0x5a, 0xdf, 0x22, 0xf5, 0x02, 0xad, 0x43, 0xbf, 0xdf, 0x16, 0x32, 0x23,
	0x41, 0x5e, 0x96, 0x46, 0x3c, 0x39, 0xa2, 0xce, 0xab, 0xf2, 0x8d, 0x21, 0x91, 0x96, 0x49, 0x64,
	0x8f, 0xec, 0x14, 0x4e, 0x24, 0x7d, 0xc6, 0xc9, 0x7f, 0x74, 0x61, 0xf0, 0x48, 0x79, 0xa7, 0x38,
	0x1e, 0x87, 0x76, 0x99, 0x96, 0x90, 0xc3, 0xae, 0xc9, 0xe1, 0x09, 0x69, 0x14, 0xce, 0x41, 0x35,
	0xde, 0x9d, 0x0c, 0x5c, 0x74, 0x3a, 0x70, 0xd1, 0xef, 0x81, 0x8b, 0xbe, 0x0c, 0xdd, 0xca, 0xe9,
	0xd0, 0xad, 0xfc, 0x1c, 0xba, 0x95, 0xd7, 0xbb, 0x41, 0xa8, 0xf7, 0xfb, 0xdd, 0x9a, 0x2f, 0xa2,
	0x89, 0x3a, 0xa3, 0xef, 0x8e, 0x75, 0x7c, 0x31, 0x72, 0xdc, 0x32, 0x8e, 0x47, 0x33, 0x2a, 0xe9,
	0x63, 0xc9, 0x55, 0xb7, 0x6a, 0xfe, 0x83, 0x8f, 0xce, 0x02, 0x00, 0x00, 0xff, 0xff, 0x56, 0x3f,
	0x16, 0xe3, 0x64, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a Passport by index.
	Passport(ctx context.Context, in *QueryGetPassportRequest, opts ...grpc.CallOption) (*QueryGetPassportResponse, error)
	// Queries a PassportStorage by index.
	PassportStorage(ctx context.Context, in *QueryGetPassportStorageRequest, opts ...grpc.CallOption) (*QueryGetPassportStorageResponse, error)
	// Queries a Passports by index.
	Passports(ctx context.Context, in *QueryGetPassportsRequest, opts ...grpc.CallOption) (*QueryGetPassportsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/SmplFinance.smplsecretsvaultchain.smplsecretsvaultchain.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Passport(ctx context.Context, in *QueryGetPassportRequest, opts ...grpc.CallOption) (*QueryGetPassportResponse, error) {
	out := new(QueryGetPassportResponse)
	err := c.cc.Invoke(ctx, "/SmplFinance.smplsecretsvaultchain.smplsecretsvaultchain.Query/Passport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PassportStorage(ctx context.Context, in *QueryGetPassportStorageRequest, opts ...grpc.CallOption) (*QueryGetPassportStorageResponse, error) {
	out := new(QueryGetPassportStorageResponse)
	err := c.cc.Invoke(ctx, "/SmplFinance.smplsecretsvaultchain.smplsecretsvaultchain.Query/PassportStorage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Passports(ctx context.Context, in *QueryGetPassportsRequest, opts ...grpc.CallOption) (*QueryGetPassportsResponse, error) {
	out := new(QueryGetPassportsResponse)
	err := c.cc.Invoke(ctx, "/SmplFinance.smplsecretsvaultchain.smplsecretsvaultchain.Query/Passports", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a Passport by index.
	Passport(context.Context, *QueryGetPassportRequest) (*QueryGetPassportResponse, error)
	// Queries a PassportStorage by index.
	PassportStorage(context.Context, *QueryGetPassportStorageRequest) (*QueryGetPassportStorageResponse, error)
	// Queries a Passports by index.
	Passports(context.Context, *QueryGetPassportsRequest) (*QueryGetPassportsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Passport(ctx context.Context, req *QueryGetPassportRequest) (*QueryGetPassportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Passport not implemented")
}
func (*UnimplementedQueryServer) PassportStorage(ctx context.Context, req *QueryGetPassportStorageRequest) (*QueryGetPassportStorageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PassportStorage not implemented")
}
func (*UnimplementedQueryServer) Passports(ctx context.Context, req *QueryGetPassportsRequest) (*QueryGetPassportsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Passports not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SmplFinance.smplsecretsvaultchain.smplsecretsvaultchain.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Passport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetPassportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Passport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SmplFinance.smplsecretsvaultchain.smplsecretsvaultchain.Query/Passport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Passport(ctx, req.(*QueryGetPassportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PassportStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetPassportStorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PassportStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SmplFinance.smplsecretsvaultchain.smplsecretsvaultchain.Query/PassportStorage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PassportStorage(ctx, req.(*QueryGetPassportStorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Passports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetPassportsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Passports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SmplFinance.smplsecretsvaultchain.smplsecretsvaultchain.Query/Passports",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Passports(ctx, req.(*QueryGetPassportsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "SmplFinance.smplsecretsvaultchain.smplsecretsvaultchain.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Passport",
			Handler:    _Query_Passport_Handler,
		},
		{
			MethodName: "PassportStorage",
			Handler:    _Query_PassportStorage_Handler,
		},
		{
			MethodName: "Passports",
			Handler:    _Query_Passports_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "smplsecretsvaultchain/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetPassportRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPassportRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPassportRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetPassportResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPassportResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPassportResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Passport.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetPassportStorageRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPassportStorageRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPassportStorageRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetPassportStorageResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPassportStorageResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPassportStorageResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.PassportStorage.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetPassportsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPassportsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPassportsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetPassportsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPassportsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPassportsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Passports.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetPassportRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetPassportResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Passport.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetPassportStorageRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetPassportStorageResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.PassportStorage.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetPassportsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetPassportsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Passports.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPassportRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPassportRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPassportRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPassportResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPassportResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPassportResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Passport", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Passport.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPassportStorageRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPassportStorageRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPassportStorageRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPassportStorageResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPassportStorageResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPassportStorageResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PassportStorage", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PassportStorage.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPassportsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPassportsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPassportsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPassportsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPassportsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPassportsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Passports", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Passports.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
